name: purge-netlify-cache

on:
  push:
    branches:
      - main

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make POST request to Netlify API
      env:
        BEARER_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: |
        curl -X POST https://api.netlify.com/api/v1/purge \
        -H "Authorization: Bearer $BEARER_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"site_id": "4b87970e-40d8-49de-abc9-ca84e934da23"}'

